// microfrontend/dynamic_remote/react/host/src/App.jsx
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom'
import { useState, useEffect } from 'react'
// import reactLogo from './assets/react.svg'
// import viteLogo from '/vite.svg'
import './App.css'
import { lazy, Suspense } from 'react'
import { loadRemote } from './loadRemote'

const ButtonRemoteComponent = lazy(() => loadRemote('remote', 'http://localhost:3001', './Button'))
// const TextRemoteComponent = lazy(() => loadRemote('remote', 'http://localhost:3001', './Text'))
// const AppRemoteView = lazy(() => loadRemote('remote', 'http://localhost:3001', './AppView'))
// const AboutRemoteView = lazy(() => loadRemote('remote', 'http://localhost:3001', './AboutView'))
// const ProfileRemoteView = lazy(() => loadRemote('remote', 'http://localhost:3001', './ProfileView'))

function App() {
  // const [count, setCount] = useState(0)
    const [ButtonRemoteComponent, setButtonRemoteComponent] = useState(null);

    useEffect(() => {
        loadRemote('remote', 'http://localhost:3001', './Button')
        .then((module) => {
          setButtonRemoteComponent(() => module);
        })
        .catch((err) => {
            console.error('Gagal memuat modul remote:', err);
        });
    }, []);

    return (
        <>
      {/* <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div> */}
      {/* <h1>Vite + React</h1> */}
      {/* <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div> */}
      {/* <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p> */}
            <ButtonRemoteComponent />
            {/* <TextRemoteComponent /> */}
            {/* <BrowserRouter>
                <nav>
                    <Link to="/">App</Link>
                    <Link to="/about">About</Link>
                    <Link to="/profile">Profile</Link>
                </nav>
                <Routes>
                    <Route path='/' element={<Suspense fallback="Loading..."><AppRemoteView /></Suspense>} />
                    <Route path='/about' element={<Suspense fallback="Loading..."><AboutRemoteView /></Suspense>} />
                    <Route path='/profile' element={<Suspense fallback="Loading..."><ProfileRemoteView /></Suspense>} />
                </Routes>
            </BrowserRouter> */}
        </>
    )
}

export default App

// microfrontend/static/svelte/host/src/App.svelte
<script>
  // import svelteLogo from './assets/svelte.svg'
  // import viteLogo from '/vite.svg'
  // import Counter from './lib/Counter.svelte'
    import { onMount } from 'svelte';
    import Loading from './lib/Loading.svelte'
    import ErrorFallback from './lib/ErrorFallback.svelte'
    // let Button
    // let Text
    // import('remote/Button').then((module) => {
    //     Button = module.default;
    // });
    // import('remote/Text').then((module) => {
    //     Text = module.default;
    // });
    // let Button = Loading;
    // let Text = Loading;
    // let errorMessage = "";
    let Button

    // function loadRemoteEntry(url) {
    //     return new Promise((resolve, reject) => {
    //         const script = document.createElement('script');
    //         script.src = url;
    //         script.type = 'text/javascript';
    //         script.async = true;
    //         script.onload = () => resolve();
    //         script.onerror = () => reject(new Error(`Failed to load remote entry ${url}`));
    //         document.head.appendChild(script);
    //     });
    // }

    onMount(async () => {
        // try {
            // console.log("remote entry belum masuk")
            // await loadRemoteEntry('http://localhost:3001/assets/remoteEntry.js');
            // console.log("remote entry masuk")
            const buttonRemote = await import('remote/Button');
            Button = buttonRemote.default;
            // const textRemote = await import('remote/Text');
            // Text = textRemote.default;
        // } catch (err) {
        //     console.error('Error loading remote', err);
        //     errorMessage = `Error: ${err.message || 'Failed to load component.'}`;
        //     Button = ErrorFallback;
        //     Text = ErrorFallback;
        // }
  });
</script>

<main>
  <!-- <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div> -->
  <!-- <h1>Vite + Svelte</h1> -->

  <!-- <div class="card">
    <Counter />
  </div> -->

  <!-- <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p> -->

  <!-- <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p> -->
    <!-- <Button /> -->
    <span>This is a svelte host</span>
    <!-- <Button {errorMessage} /> -->
    <!-- <Text {errorMessage} /> -->
    {#if Button}
        <svelte:component this={Button} name="Button Host App" />
    {:else}
        <p>Loading Button remote component...</p>
    {/if}

    <!-- {#if Text}
        <svelte:component this={Text} name="Text Host App" />
    {:else}
        <p>Loading Text remote component...</p>
    {/if} -->
</main>

<style>
  /* .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  } */
  /* .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  } */
  /* .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  } */
  /* .read-the-docs {
    color: #888;
  } */
</style>
