// systemjs/vue-host/src/App.vue
<script setup>
// import HelloWorld from './components/HelloWorld.vue'
  import { ref, onMounted, markRaw } from 'vue'
  // import SystemJS from 'systemjs'
  // import * as SystemJS from 'systemjs'
  import Fallback from "./components/Fallback.vue"

  // SystemJS.import('http://localhost:4173/vue-remote.umd.cjs').then((mod) => {
  //   const { ComponentA, ComponentB, ComponentC } = mod;
  // })
  // const componentA = ref(Fallback)
  const componentA = ref(markRaw(Fallback))
  const componentB = ref(null)
  const componentC = ref(null)
  onMounted(async () => {
    try {
      // const mod = await SystemJS.import('http://localhost:4173/vue-remote.umd.cjs')
      const mod = await System.import('http://localhost:4173/vue-remote.umd.js')
      // componentA.value = mod.ComponentA
      componentA.value = markRaw(mod.ComponentA)
      // componentB.value = mod.ComponentB
      componentB.value = markRaw(mod.ComponentB)
      // componentC.value = mod.ComponentC
      componentC.value = markRaw(mod.ComponentC)
    } catch(e) {
      console.log("e:", e)
    }
  })
</script>

<template>
  <!-- <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div> -->
  <!-- <HelloWorld msg="Vite + Vue" /> -->
  <h1 class="bg-blue-500 text-5xl">Root</h1>
  <RouterView/>

  <component :is="componentA" v-if="componentA" />
  <component :is="componentB" v-if="componentB" />
  <component :is="componentC" v-if="componentC" />
</template>

<style scoped>
/* .logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
} */
</style>

// systemjs/react-host/src/App.jsx
'use client'
import { useEffect, useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
// import * as SystemJS from 'systemjs'

function App() {
  const [count, setCount] = useState(0)
  const [ComponentA, setComponentA] = useState(null)
  const [ComponentB, setComponentB] = useState(null)
  const [ComponentC, setComponentC] = useState(null)

  useEffect(() => {
    console.log(1)
    const loadComponent = async() => {
      console.log(2)
      try {
        console.log(3)
        // const mod = await SystemJS.import('http://localhost:4173/react-remote.umd.js');
        const mod = await System.import('http://localhost:4173/react-remote.umd.js');
        // const mod = await System.import('http://localhost:4173/vue-remote.umd.js');
        console.log(4)
        setComponentA(() => mod.ComponentA)
        console.log(5, ComponentA)
        setComponentB(() => mod.ComponentB)
        console.log(6, ComponentB)
        setComponentC(() => mod.ComponentC)
        console.log(7, ComponentC)
      } catch(e) {
        console.log(8)
        console.log("e:", e)
      }
    }
    loadComponent()
    console.log(9)
  }, [])

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>

      <h1>Component</h1>
      {ComponentA != undefined && ComponentA != null ? console.log("ComponentA:", ComponentA) : <p>Loading...</p>}
      {ComponentA != undefined && ComponentA != null ? <ComponentA /> : <p>Loading...</p>}
      {/* {ComponentB ? <ComponentB /> : <p>Loading...</p>} */}
      {/* {ComponentC ? <ComponentC /> : <p>Loading...</p>} */}

    </>
  )
}

export default App
