// microfrontend/static/svelte/remote/src/App.svelte
<script>
  // import svelteLogo from './assets/svelte.svg'
  // import viteLogo from '/vite.svg'
  // import Counter from './lib/Counter.svelte'
    import Button from './lib/Button.svelte'
    import Text from './lib/Text.svelte'
</script>

<main>
  <!-- <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div> -->
  <!-- <h1>Vite + Svelte</h1> -->

  <!-- <div class="card">
    <Counter />
  </div> -->

  <!-- <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p> -->

  <!-- <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p> -->
    <Button />
    <Text />
</main>

<style>
  /* .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  } */
  /* .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  } */
  /* .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  } */
  /* .read-the-docs {
    color: #888;
  } */
</style>

// microfrontend/dynamic/vue/remote2/src/App.vue
<script setup>
// import HelloWorld from './components/HelloWorld.vue'
    import Button from './components/Button.vue'
    import Text from './components/Text.vue'
    import AppView from './views/AppView.vue'
    import AboutView from './views/AboutView.vue'
    import ProfileView from './views/ProfileView.vue'
</script>

<template>
  <!-- <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div> -->
  <!-- <HelloWorld msg="Vite + Vue" /> -->
    <Button />
    <Text />
    <p>
        <strong>Current route path:</strong> {{ $route.fullPath }}
    </p>
    <nav>
        <RouterLink to="/">App </RouterLink>
        <RouterLink to="/about">About </RouterLink>
        <RouterLink to="/profile">Profile </RouterLink>
    </nav>
    <main>
        <RouterView />
    </main>
</template>

<style scoped>
/* .logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
} */
/* .logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
} */
/* .logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
} */
</style>
